# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Event

# Model Form Field configuration
form: $/kurtjensen/mycalendar/models/event/fields.yaml

# Model Class name
modelClass: KurtJensen\MyCalendar\Models\Event

# Default redirect location
defaultRedirect: kurtjensen/mycalendar/events

# Create page
create:
    title: Create Event
    redirect: kurtjensen/mycalendar/events/update/:id
    redirectClose: kurtjensen/mycalendar/events

# Update page
update:
    title: Edit Event
    redirect: kurtjensen/mycalendar/events
    redirectClose: kurtjensen/mycalendar/events

# Preview page
preview:
    title: Preview Event